package com.reta.dao;

import com.reta.bean.Flink;
import com.reta.bean.FlinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FlinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    long countByExample(FlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int deleteByExample(FlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int insert(Flink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int insertSelective(Flink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    List<Flink> selectByExample(FlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    Flink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Flink record, @Param("example") FlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int updateByExample(@Param("record") Flink record, @Param("example") FlinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int updateByPrimaryKeySelective(Flink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flink
     *
     * @mbg.generated Thu Aug 15 14:10:12 CST 2019
     */
    int updateByPrimaryKey(Flink record);
}